# Generated by Django 3.1.3 on 2021-12-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='murl',
            field=models.CharField(default='murl', max_length=1000),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(default='url', max_length=1000),
        ),
    ]
