# Generated by Django 3.1.3 on 2021-12-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0002_auto_20211202_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='done',
            field=models.IntegerField(default=1),
        ),
    ]
