# Generated by Django 3.1.3 on 2021-12-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0003_url_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='murl',
            new_name='themurl',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='url',
            new_name='theurl',
        ),
    ]
